
# Use official Node.js LTS image
FROM node:18

# Set working directory inside the container
WORKDIR /

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose port 3000
EXPOSE 3001

# Start the app
CMD ["npm", "start"]
