apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend


    spec:
      containers:
      imagePullSecrets:
      - name: regcred

      - name: frontend
        image: wxpua/practice:frontend
        ports:
        - containerPort: 3001
        envFrom:
          - configMapRef:
              name: name-cm
          - configMapRef:
              name: backend-url
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3001







